<?php
/**
 * @file vc.module
 */

/**
 * Autoloading…
 */
include_once dirname(__FILE__) . '/vc.autoload.inc';

/**
 * Implements hook_vc_api().
 */
function vc_vc_api() {
  return array('api' => '1.0');
}

/**
 * Wrapper function to work with configuration value of a module.
 *
 * @see README.txt > Configuration System
 */
function vc_conf($path) {
  static $config;

  if (!$config) {
    $config = new VcConfig($path);
  }

  return $config;
}

/**
 * Get modules support vc.
 */
function vc_get_module_apis($api = 'vc', $reset = FALSE) {
  if ($reset) {
    $cache = &drupal_static('ctools_plugin_api_info');
    if (isset($cache['vc'][$api])) {
      unset($cache['vc'][$api]);
    }
  }

  ctools_include('plugins');
  $return = ctools_plugin_api_info('vc', $api, '1.0', '1.0');

  // Make sure lazy load alway works
  $return['vc'] = array('version' => '1.0', 'path' => dirname(__FILE__));

  return $return;
}

/**
 * Tell ctools our hook name.
 */
function vc_ctools_plugin_api_hook_name() {
  return 'vc_api';
}

/**
 * Wrapper function to cache
 */
function vc_cache() {
  $args = func_get_args();
  $a1 = array_shift($args);

  // Check reset flag
  $reset = !empty($_GET['nocache']);
  if (is_bool($a1)) {
    $reset = TRUE;
    $a1 = array_shift($args);
  }

  $cache_id = substr(md5(serialize($args)), 0, 10);
  if (!$reset && $cache = cache_get($cache_id)) {
    if ($cache->expire == CACHE_PERMANENT) return $cache->data;
    if ($cache->expire == CACHE_TEMPORARY) return $cache->data;
    if ($cache->expire >= time()) return $cache->data;
  }

  $is_function = is_string($a1);
  $is_object = is_object($a1);

  if (!$is_function && !$is_object) {
    throw new Exception('Wrong parameter');
  }

  if ($is_function) {
    $return = call_user_func_array($a1, $args);
  }
  else {
    $method = array_shift($args);
    $return = @call_user_method_array($method, $a1, $args);
  }

  if (!is_null($return)) {
    if ($is_function) $comment = new ReflectionFunction($a1);
    if ($is_object) {
      $comment = new ReflectionObject($a1);
      $comment = $comment->getMethod($method);
    }
    $comment = $comment->getDocComment();
    preg_match('/@ttl\s+(.+)\n/', $comment, $matches);
    $ttl = !empty($matches) ? strtotime(trim($matches[1], "\r\s'")) : CACHE_PERMANENT;
    cache_set($cache_id, $return, 'cache', $ttl);
    return $return;
  }
}

/**
 * Build lazy content.
 *
 * @param string $path
 * @return type
 */
function vc_content($path) {
  return Vc_Lazy_Content::build($path);
}

/**
 * Litle wrapper for views_ui
 */
function vc_embed_view($options) {
  $name       = $options['name'];
  $display_id = !empty($options['display_id']) ? $options['display_id'] : 'default';
  $path       = !empty($options['path']) ? $options['path'] : NULL;

  $args = func_get_args();
  array_shift($args); // remove $options

  if (!empty($options['json'])) {
    if (module_exists('views_json')) {
      return $return = views_json_get($name, $display_id, $args);
    }
  }

  $view = views_get_view($name);

  if (!$view || !$view->access($display_id)) {
    return;
  }

  if (!empty($path)) {
    $view->override_path = $path;
  }

  return $view->preview($display_id, $args);
}

/**
 * Help function to get global variable.
 */
function vc_global($key) {
  return isset($GLOBALS[$key]) ? $GLOBALS[$key] : NULL;
}

/**
 * Legacy for yaml_parse(), yaml_parse_file().
 */
if (!function_exists('yaml_parse')) {
  function yaml_parse($string) {
    $yaml = new Symfony\Component\Yaml\Parser();
    return $yaml->parse($string);
  }

  function yaml_parse_file($file) {
    $yaml = new Symfony\Component\Yaml\Parser();
    return $yaml->parse(file_get_contents($file));
  }

  function yaml_parse_url($url) {
    $yaml = new Symfony\Component\Yaml\Parser();
    return $yaml->parse(file_get_contents($url));
  }

  function yaml_emit($data) {
    $yaml = new Symfony\Component\Yaml\Dumper();
    return $dumper->dump($data);
  }
}

/**
 * Wrapper for form validators.
 *
 * @param type $form
 * @param type $form_state
 */
function vc_form_validate($form, &$form_state) {
  if (!empty($form['#vc_validate']));

  foreach ($form['#vc_validate'] as $validate) {
    call_user_func($validate, $form, $form_state);
  }
}

/**
 * Wrapper for form submit callbacks.
 */
function vc_form_submit($form, &$form_state) {
  if (!empty($form['#vc_submit']));

  foreach ($form['#vc_submit'] as $submit) {
    call_user_func($submit, $form, $form_state);
  }
}
