<?php
/**
 * @file vc_examples.module
 *
 * Example module for vc module.
 */

/**
 * Implements hook_vc_api().
 */
function vc_example_vc_api() {
  return array('api' => '1.0');
}

/**
 * Try lazy loading.
 */
function vc_example_lazy_load() {
  $object = new VcExample();
  kpr($object->hello());

  $object = new VcExampleLazy();
  kpr($object->hi());

  exit;
}

/**
 * Callback for /vc_example.
 */
function vc_example_page_callback($a1 = 'A1') {
  return array(
    '#theme' => 'item_list',
    '#items' => array(
      "Argument 1: " . print_r($a1, TRUE),
      "Time: " . format_date(time()),
      "Micro Time: " . microtime(),
    )
  );
}
